# Generated by Django 4.2.16 on 2026-05-29 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='F.I.Sh.')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('initials', models.CharField(blank=True, max_length=5, verbose_name='Bosh harflar')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='Lavozim')),
                ('org', models.CharField(blank=True, max_length=300, verbose_name='Tashkilot')),
                ('degree', models.CharField(blank=True, max_length=200, verbose_name='Ilmiy daraja')),
                ('bio', models.TextField(blank=True, verbose_name='Tarjimai hol')),
                ('avatar_idx', models.PositiveSmallIntegerField(default=0, verbose_name='Avatar rangi (0–4)')),
                ('is_top', models.BooleanField(default=False, verbose_name='Top muallif')),
                ('is_new', models.BooleanField(default=False, verbose_name='Yangi')),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
                'ordering': ['name'],
            },
        ),
    ]
