# Generated by Django 4.2.16 on 2026-05-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='authors/avatars/', verbose_name='Rasm (Telegram orqali yuklangan)'),
        ),
        migrations.AddField(
            model_name='author',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram chat ID'),
        ),
        migrations.AddField(
            model_name='author',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Telegram @username'),
        ),
    ]
