# Generated by Django 4.2.16 on 2026-05-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_avatar_author_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_top',
        ),
    ]
