# Generated by Django 4.2.16 on 2026-05-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_remove_author_is_new_remove_author_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_views',
            field=models.PositiveIntegerField(default=0, verbose_name="Profil ko'rilishi soni"),
        ),
    ]
