# Generated by Django 4.2.16 on 2026-06-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_author_profile_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='source',
            field=models.CharField(choices=[('telegram', 'Telegram bot'), ('manual', "Qo'lda (admin)"), ('parser', 'PDF parser')], default='manual', max_length=10, verbose_name='Manba'),
        ),
    ]
