# Generated by Django 4.2.16 on 2026-09-18 08:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_backfill_author_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Eski slug')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Izoh')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='authors.author', verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Muallifning eski manzili',
                'verbose_name_plural': 'Mualliflarning eski manzillari',
                'ordering': ['slug'],
            },
        ),
    ]
