# Generated by Django 4.2.16 on 2026-09-18 09:50

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_authoralias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='authors/avatars/', validators=[utils.validators.FileKindValidator(('.jpg', '.jpeg', '.jpe', '.png', '.gif', '.webp', '.bmp', '.tif', '.tiff', '.heic', '.heif', '.avif', '.ico'), 15728640, 'Rasm')], verbose_name='Rasm (Telegram orqali yuklangan)'),
        ),
    ]
