# Generated by Django 4.2.16 on 2026-09-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_alter_author_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Elektron pochta'),
        ),
        migrations.AddField(
            model_name='author',
            name='orcid',
            field=models.CharField(blank=True, help_text="0000-0002-1825-0097 ko'rinishida", max_length=19, verbose_name='ORCID'),
        ),
        migrations.AddField(
            model_name='author',
            name='scopus_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='Scopus Author ID'),
        ),
    ]
