# Generated by Django 4.2.16 on 2026-05-30 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Telegram chat ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Ism (eslatma uchun)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Telegram admin',
                'verbose_name_plural': 'Telegram adminlar (bildirishnoma)',
                'ordering': ['name'],
            },
        ),
    ]
