# Generated by Django 4.2.16 on 2026-09-18 07:59

import apps.partner.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Masalan: "Ilmiy indekslash xizmati"', max_length=200, verbose_name='Hamkor nomi')),
                ('client_id', models.CharField(db_index=True, default=apps.partner.models.generate_client_id, max_length=64, unique=True, verbose_name='client_id')),
                ('secret_hash', models.CharField(blank=True, max_length=256, verbose_name='client_secret (xesh)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('contact', models.CharField(blank=True, max_length=300, verbose_name='Aloqa (email/telefon)')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi murojaat')),
                ('request_count', models.PositiveBigIntegerField(default=0, verbose_name="So'rovlar soni")),
            ],
            options={
                'verbose_name': 'Hamkor mijoz (API)',
                'verbose_name_plural': 'Hamkor mijozlar (API)',
                'ordering': ['name'],
            },
        ),
    ]
