# Generated by Django 4.2.16 on 2026-09-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerclient',
            name='token_version',
            field=models.PositiveIntegerField(default=1, verbose_name='Token versiyasi'),
        ),
    ]
