# Generated by Django 4.2.16 on 2026-09-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_partnerclient_token_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRequestDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('count', models.PositiveIntegerField(default=0, verbose_name="So'rovlar")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='partner.partnerclient', verbose_name='Hamkor')),
            ],
            options={
                'verbose_name': "Hamkor so'rovlari (kunlik)",
                'verbose_name_plural': "Hamkor so'rovlari (kunlik)",
                'ordering': ['-date'],
                'unique_together': {('client', 'date')},
            },
        ),
    ]
