# Generated by Django 4.2.16 on 2026-07-17 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentralAsiaPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('scraped', 'einfolib.uz (parse)'), ('manual', "Qo'lda qo'shilgan")], default='manual', max_length=10, verbose_name='Manba')),
                ('source_url', models.URLField(blank=True, max_length=800, null=True, unique=True, verbose_name='Manba URL')),
                ('source_slug', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Manba slug (einfolib.uz)')),
                ('source_category', models.CharField(blank=True, default='Central Asia', max_length=200, verbose_name="Manba bo'limi")),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=520, unique=True, verbose_name='Slug (URL)')),
                ('author_line', models.CharField(blank=True, max_length=500, verbose_name='Muallif (matn)')),
                ('excerpt', models.TextField(blank=True, verbose_name='Qisqacha mazmun')),
                ('content', models.TextField(blank=True, verbose_name='Tarkib (HTML)')),
                ('doi', models.CharField(blank=True, max_length=200, verbose_name='DOI')),
                ('image', models.ImageField(blank=True, null=True, upload_to='central_asia/%Y/%m/', verbose_name='Rasm (ixtiyoriy)')),
                ('views_scraped', models.PositiveIntegerField(default=0, verbose_name='Manba view')),
                ('views_local', models.PositiveIntegerField(default=0, verbose_name='Bizning view')),
                ('quote_number', models.PositiveIntegerField(default=0, verbose_name='Iqtiboslar (quote)')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Nashr sanasi')),
                ('is_published', models.BooleanField(default=True, verbose_name="E'lon qilingan")),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi parse')),
            ],
            options={
                'verbose_name': 'Central Asia maqolasi',
                'verbose_name_plural': 'Central Asia maqolalari',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='central_asi_created_839a57_idx'), models.Index(fields=['is_published'], name='central_asi_is_publ_b27706_idx')],
            },
        ),
    ]
