# Generated by Django 4.2.16 on 2026-07-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_asia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centralasiapost',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Central Asia maqolasi', 'verbose_name_plural': 'Central Asia maqolalari'},
        ),
        migrations.AddField(
            model_name='centralasiapost',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Tartib (parse)'),
        ),
    ]
