# Generated by Django 4.2.16 on 2026-05-29 15:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journals', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=520, unique=True, verbose_name='Slug (URL)')),
                ('excerpt', models.TextField(blank=True, verbose_name='Qisqacha mazmun')),
                ('content', models.TextField(blank=True, verbose_name="Tarkib (HTML — avtomatik to'ldiriladi)")),
                ('source_file', models.FileField(blank=True, help_text='Faylni saqlashda tarkib (HTML) avtomatik parse qilinadi.', null=True, upload_to='articles/sources/%Y/%m/', verbose_name='Manba fayl (.docx yoki .pdf)')),
                ('status', models.CharField(choices=[('open', 'Ochiq kirish'), ('lock', 'Obunachi')], default='open', max_length=10, verbose_name='Holat')),
                ('year', models.PositiveIntegerField(default=2026, verbose_name='Yil')),
                ('quarter', models.PositiveSmallIntegerField(default=1, verbose_name='Chorak (1–4)')),
                ('pages', models.PositiveIntegerField(default=0, verbose_name='Sahifalar soni')),
                ('min_read', models.PositiveIntegerField(default=5, verbose_name="O'qish (daqiqa)")),
                ('cites', models.PositiveIntegerField(default=0, verbose_name='Iqtiboslar')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
                ('img_variant', models.PositiveSmallIntegerField(default=0, verbose_name='Thumbnail varianti (0–3)')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Nashr sanasi')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
            options={
                'verbose_name': 'Maqola muallifi',
                'verbose_name_plural': 'Maqola mualliflari',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='articles', through='articles.ArticleAuthor', to='authors.author', verbose_name='Mualliflar'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.category', verbose_name="Yo'nalish"),
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='journals.issue', verbose_name='Jurnal soni'),
        ),
    ]
