# Generated by Django 4.2.16 on 2026-05-29 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_avatar_author_telegram_chat_id_and_more'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.BigIntegerField(db_index=True, verbose_name='Telegram chat ID')),
                ('tg_name', models.CharField(blank=True, max_length=200, verbose_name='Ism (Telegram)')),
                ('tg_username', models.CharField(blank=True, max_length=150, verbose_name='@username')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (ixtiyoriy)')),
                ('source_file', models.FileField(upload_to='submissions/%Y/%m/', verbose_name='Yuborilgan fayl')),
                ('note', models.TextField(blank=True, verbose_name='Muallif izohi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('reject_reason', models.TextField(blank=True, verbose_name='Rad etish sababi')),
                ('article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='articles.article', verbose_name='Yaratilgan maqola')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='authors.author', verbose_name='Muallif profili')),
            ],
            options={
                'verbose_name': 'Yuborilgan maqola',
                'verbose_name_plural': 'Yuborilgan maqolalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
