# Generated by Django 4.2.16 on 2026-05-30 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlesubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name="Kalit so'z")),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
            options={
                'verbose_name': "Kalit so'z",
                'verbose_name_plural': "Kalit so'zlar",
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='references',
            field=models.TextField(blank=True, verbose_name='Adabiyotlar (References)'),
        ),
        migrations.AddField(
            model_name='articlesubmission',
            name='abstract',
            field=models.TextField(blank=True, verbose_name='Annotatsiya (abstract)'),
        ),
        migrations.AddField(
            model_name='articlesubmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/images/%Y/%m/', verbose_name='Maqola rasmi'),
        ),
        migrations.AddField(
            model_name='articlesubmission',
            name='keywords',
            field=models.TextField(blank=True, verbose_name="Kalit so'zlar (vergul bilan)"),
        ),
        migrations.AddField(
            model_name='articlesubmission',
            name='references',
            field=models.TextField(blank=True, verbose_name='Adabiyotlar (references)'),
        ),
        migrations.AddField(
            model_name='articlesubmission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, verbose_name='Qisqacha mazmun (abstract)'),
        ),
        migrations.AlterField(
            model_name='articlesubmission',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='Rad etish / bekor qilish sababi'),
        ),
        migrations.AlterField(
            model_name='articlesubmission',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/', verbose_name='Yuborilgan fayl'),
        ),
        migrations.AlterField(
            model_name='articlesubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='draft', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='articlesubmission',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.keyword', verbose_name="Kalit so'zlar"),
        ),
    ]
