# Generated by Django 4.2.16 on 2026-05-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_keyword_article_references_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesubmission',
            name='ai_filled',
            field=models.BooleanField(default=False, verbose_name="AI to'ldirgan"),
        ),
        migrations.AddField(
            model_name='articlesubmission',
            name='extracted_authors',
            field=models.TextField(blank=True, verbose_name='Mualliflar (AI, vergul bilan)'),
        ),
        migrations.AddField(
            model_name='articlesubmission',
            name='extracted_text',
            field=models.TextField(blank=True, verbose_name='Fayldan ajratilgan xom matn'),
        ),
    ]
