# Generated by Django 4.2.16 on 2026-05-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articlesubmission_ai_filled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_names',
            field=models.TextField(blank=True, verbose_name='Mualliflar (matn, AI, vergul bilan)'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/%Y/%m/', verbose_name='Maqola rasmi (muallif yuborgan)'),
        ),
    ]
