# Generated by Django 4.2.16 on 2026-06-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_author_names_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='llm_document_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Local LLM document ID'),
        ),
    ]
