# Generated by Django 4.2.16 on 2026-06-24 17:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_issue_pdf_file'),
        ('articles', '0006_article_llm_document_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('section', models.CharField(blank=True, max_length=300, verbose_name="Bo'lim")),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha')),
                ('author_name', models.CharField(blank=True, max_length=200, verbose_name='Ism familiya')),
                ('extra_info', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot")),
                ('start_page', models.PositiveIntegerField(blank=True, null=True, verbose_name='Boshlanish bet')),
                ('end_page', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tugash bet')),
                ('article_pdf', models.FileField(blank=True, null=True, upload_to='parsed/%Y/%m/', verbose_name='Ajratilgan maqola PDF')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parsed/photos/%Y/%m/', verbose_name='Muallif rasmi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('saved', 'Saqlangan'), ('skipped', "O'tkazib yuborilgan")], default='pending', max_length=10, verbose_name='Holat')),
                ('article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_source', to='articles.article', verbose_name='Yaratilgan maqola')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_articles', to='journals.issue', verbose_name='Jurnal soni')),
            ],
            options={
                'verbose_name': 'Ajratilgan maqola (parser)',
                'verbose_name_plural': 'Ajratilgan maqolalar (parser)',
                'ordering': ['order'],
            },
        ),
    ]
