# Generated by Django 4.2.16 on 2026-09-18 09:50

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_parsedarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/%Y/%m/', validators=[utils.validators.FileKindValidator(('.jpg', '.jpeg', '.jpe', '.png', '.gif', '.webp', '.bmp', '.tif', '.tiff', '.heic', '.heif', '.avif', '.ico'), 15728640, 'Rasm')], verbose_name='Maqola rasmi (muallif yuborgan)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_file',
            field=models.FileField(blank=True, help_text='Faylni saqlashda tarkib (HTML) avtomatik parse qilinadi.', null=True, upload_to='articles/sources/%Y/%m/', validators=[utils.validators.FileKindValidator(('.pdf', '.doc', '.docx', '.docm', '.dot', '.dotx', '.rtf', '.odt'), 52428800, 'Hujjat')], verbose_name='Manba fayl (.docx yoki .pdf)'),
        ),
        migrations.AlterField(
            model_name='articlesubmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/images/%Y/%m/', validators=[utils.validators.FileKindValidator(('.jpg', '.jpeg', '.jpe', '.png', '.gif', '.webp', '.bmp', '.tif', '.tiff', '.heic', '.heif', '.avif', '.ico'), 15728640, 'Rasm')], verbose_name='Maqola rasmi'),
        ),
        migrations.AlterField(
            model_name='articlesubmission',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/', validators=[utils.validators.FileKindValidator(('.pdf', '.doc', '.docx', '.docm', '.dot', '.dotx', '.rtf', '.odt'), 52428800, 'Hujjat')], verbose_name='Yuborilgan fayl'),
        ),
        migrations.AlterField(
            model_name='parsedarticle',
            name='article_pdf',
            field=models.FileField(blank=True, null=True, upload_to='parsed/%Y/%m/', validators=[utils.validators.FileKindValidator(('.pdf', '.doc', '.docx', '.docm', '.dot', '.dotx', '.rtf', '.odt'), 52428800, 'Hujjat')], verbose_name='Ajratilgan maqola PDF'),
        ),
        migrations.AlterField(
            model_name='parsedarticle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='parsed/photos/%Y/%m/', validators=[utils.validators.FileKindValidator(('.jpg', '.jpeg', '.jpe', '.png', '.gif', '.webp', '.bmp', '.tif', '.tiff', '.heic', '.heif', '.avif', '.ico'), 15728640, 'Rasm')], verbose_name='Muallif rasmi'),
        ),
    ]
