# Generated by Django 4.2.16 on 2026-09-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_status_alter_article_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='page_end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tugash beti'),
        ),
        migrations.AddField(
            model_name='article',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Boshlanish beti'),
        ),
    ]
