# Generated by Django 4.2.16 on 2026-09-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_page_end_article_page_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Sana')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
            ],
            options={
                'verbose_name': "Kunlik ko'rishlar",
                'verbose_name_plural': "Kunlik ko'rishlar",
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, help_text='Songa biriktirilganda avtomatik: 10.62499/kutubxona.<yil>.<son>.<NN>', max_length=100, verbose_name='DOI'),
        ),
        migrations.AddField(
            model_name='article',
            name='udk',
            field=models.CharField(blank=True, max_length=50, verbose_name='UDK'),
        ),
        migrations.AddField(
            model_name='articlesubmission',
            name='org',
            field=models.CharField(blank=True, max_length=300, verbose_name='Tashkilot'),
        ),
        migrations.AddField(
            model_name='articlesubmission',
            name='udk',
            field=models.CharField(blank=True, max_length=50, verbose_name='UDK'),
        ),
    ]
