# Generated by Django 4.2.16 on 2026-09-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_viewday_article_doi_article_udk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesubmission',
            name='preview_html',
            field=models.TextField(blank=True, help_text="Admin sahifasi uchun; birinchi ochilganda avtomatik to'ldiriladi", verbose_name="DOCX oldindan ko'rish (HTML)"),
        ),
    ]
