# Generated by Django 4.2.16 on 2026-05-29 15:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Kutubxona Arxivi', max_length=200, verbose_name='Jurnal nomi')),
                ('issn', models.CharField(blank=True, max_length=20, verbose_name='ISSN')),
            ],
            options={
                'verbose_name': 'Jurnal',
                'verbose_name_plural': 'Jurnallar',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume', models.PositiveIntegerField(verbose_name='Jild')),
                ('number', models.PositiveIntegerField(verbose_name='Son')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('season', models.CharField(choices=[('Bahor', 'Bahor'), ('Yoz', 'Yoz'), ('Kuz', 'Kuz'), ('Qish', 'Qish')], max_length=10, verbose_name='Mavsum')),
                ('date_label', models.CharField(blank=True, max_length=100, verbose_name="Sana (ko'rinishi)")),
                ('palette', models.PositiveSmallIntegerField(default=0, verbose_name='Rang palitasi (0–5)')),
                ('is_current', models.BooleanField(default=False, verbose_name='Joriy son')),
                ('is_upcoming', models.BooleanField(default=False, verbose_name='Tayyorlanmoqda')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='journals.journal', verbose_name='Jurnal')),
            ],
            options={
                'verbose_name': 'Jurnal soni',
                'verbose_name_plural': 'Jurnal sonlari',
                'ordering': ['-year', '-number'],
                'unique_together': {('journal', 'volume', 'number')},
            },
        ),
    ]
