# Generated by Django 4.2.16 on 2026-05-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cover_image',
            field=models.ImageField(blank=True, help_text="Yuklanmasa, palette ranglari asosida default cover ko'rsatiladi.", null=True, upload_to='journals/covers/%Y/', verbose_name='Muqova rasmi (ixtiyoriy)'),
        ),
    ]
