# Generated by Django 4.2.16 on 2026-06-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_issue_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='pdf_file',
            field=models.FileField(blank=True, help_text="Jurnal sonining to'liq PDF nusxasi. Yuklansa, son sahifasida ochiladi.", null=True, upload_to='journals/pdfs/%Y/', verbose_name="PDF fayl (to'liq son)"),
        ),
    ]
