# Generated by Django 4.2.16 on 2026-09-18 09:50

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_issue_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='cover_image',
            field=models.ImageField(blank=True, help_text="Yuklanmasa, palette ranglari asosida default cover ko'rsatiladi.", null=True, upload_to='journals/covers/%Y/', validators=[utils.validators.FileKindValidator(('.jpg', '.jpeg', '.jpe', '.png', '.gif', '.webp', '.bmp', '.tif', '.tiff', '.heic', '.heif', '.avif', '.ico'), 15728640, 'Rasm')], verbose_name='Muqova rasmi (ixtiyoriy)'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='pdf_file',
            field=models.FileField(blank=True, help_text="Jurnal sonining to'liq PDF nusxasi. Yuklansa, son sahifasida ochiladi.", null=True, upload_to='journals/pdfs/%Y/', validators=[utils.validators.FileKindValidator(('.pdf', '.doc', '.docx', '.docm', '.dot', '.dotx', '.rtf', '.odt'), 52428800, 'Hujjat')], verbose_name="PDF fayl (to'liq son)"),
        ),
    ]
