# Generated by Django 4.2.16 on 2026-09-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_alter_issue_cover_image_alter_issue_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='editor_name',
            field=models.CharField(blank=True, help_text='Masalan: f.f.d. N. Qodirova', max_length=200, verbose_name='Bosh muharrir'),
        ),
        migrations.AddField(
            model_name='issue',
            name='editorial_note',
            field=models.TextField(blank=True, help_text='Son sahifasida muqova yonida chiqadigan kirish matni.', verbose_name="Tahririyat so'zi"),
        ),
        migrations.AddField(
            model_name='issue',
            name='total_pages',
            field=models.PositiveIntegerField(default=0, verbose_name='Hajmi (bet)'),
        ),
        migrations.AddField(
            model_name='issue',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar"),
        ),
    ]
