# Generated by Django 4.2.16 on 2026-05-31 12:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0004_author_profile_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloklangan')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi xabar vaqti')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name="O'qilmagan")),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='authors.author', verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chatlar',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=10)),
                ('kind', models.CharField(choices=[('text', 'Matn'), ('photo', 'Rasm'), ('document', 'Fayl')], default='text', max_length=10)),
                ('text', models.TextField(blank=True, verbose_name='Matn / caption')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat/images/%Y/%m/', verbose_name='Rasm')),
                ('document', models.FileField(blank=True, null=True, upload_to='chat/files/%Y/%m/', verbose_name='Fayl')),
                ('is_read', models.BooleanField(default=False)),
                ('tg_message_id', models.BigIntegerField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['chat', '-created_at'], name='chat_messag_chat_id_013eed_idx')],
            },
        ),
    ]
