# Generated by Django 4.2.16 on 2026-09-18 09:50

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='chat/files/%Y/%m/', validators=[utils.validators.FileKindValidator(('.pdf', '.doc', '.docx', '.docm', '.dot', '.dotx', '.rtf', '.odt', '.jpg', '.jpeg', '.jpe', '.png', '.gif', '.webp', '.bmp', '.tif', '.tiff', '.heic', '.heif', '.avif', '.ico', '.xls', '.xlsx', '.csv', '.ppt', '.pptx', '.txt', '.zip', '.rar', '.7z'), 52428800, 'Fayl')], verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/images/%Y/%m/', validators=[utils.validators.FileKindValidator(('.jpg', '.jpeg', '.jpe', '.png', '.gif', '.webp', '.bmp', '.tif', '.tiff', '.heic', '.heif', '.avif', '.ico'), 15728640, 'Rasm')], verbose_name='Rasm'),
        ),
    ]
